Repository PiyushKalyanpy/GyanaGuru, pull requests merged in 2023-05, with the labels that each got.

#111 Implemented the Search Function with Debouncing
  Components/CoursesComponents/Topbar.tsx
Labels: GSSoC’23, 💪 level 3

#117 [Feat]: Implement login with Google issue id #99 Fixed
  Components/HomeSidebar.tsx
  firebase/index.tsx
  pages/login.tsx
Labels: GSSoC’23, level 3

#200 Create pull_request_template.md
  pull_request_template.md
Labels: GSSOC’23, level 2

#241 Fixed bug for dark theme in nav bar
  Components/LandingNav.tsx
Labels: GSSOC’23, level 1
