Repository PiyushKalyanpy/GyanaGuru, pull requests merged in 2023-07, with the labels that each got.

#455 Issue #444 fixed
  components/landing/LandingThreeGrid.tsx
Labels: gssoc23, level1

#416 ESLint rules added GsSoC'23
  .eslintrc.json
Labels: gssoc23, level2

#457 Enforce npm version
  .npmrc
  package.json
Labels: gssoc23, level1

#458 Prettier rules added
  .prettierignore
  .prettierrc
  package.json
Labels: gssoc23

#470 Move PR template to .github folder
  .github/pull_request_template.md
Labels: gssoc23, level1

#509 fixing cards size in LandingThreeGrid component
  components/landing/LandingThreeGrid.tsx
Labels: gssoc23, level1

#491 Added meta tags
  pages/index.tsx
Labels: gssoc23, level2

#494 Implementing New Design for the About Us Page
  components/cards/WhyChooseGyanGuruCard.tsx
  components/landing/LandingFooter.tsx
  components/landing/LandingNav.tsx
  data/about_us.json
  data/about_why_choose.json
  pages/static/about-us.tsx
Labels: gssoc23, level3

#518 fixing navbar position
  pages/index.tsx
Labels: gssoc23, level1

#531 fix:Fixes Routing
  components/landing/LandingFooter.tsx
  components/landing/LandingNav.tsx
  next.config.js
Labels: gssoc23, level1

#529 Enabling dashbaord Page
  components/depricated/Utils/ContributionButton.tsx
  components/layouts/sidebar/DashboardSidebar.tsx
  components/util/CustomRedirectButton.tsx
  pages/dashboard/index.tsx
  pages/depricated/dashboard.tsx
Labels: gssoc23, level2

#516 Updating the router route from /courses to /dashboard on the login page
  pages/login.tsx
Labels: gssoc23, level1

#550 removing target="_blank" from the anchor tag
  src/components/landing/LandingThreeSecond.tsx
Labels: gssoc23, level1

#559 Issue #554 fixed
  src/styles/globals.css
Labels: gssoc23, level1

#553 implementing new design for faq page
  package-lock.json
  package.json
  public/images/faqsection.png
  src/components/landing/LandingContact.tsx
  src/data/faq.json
  src/pages/static/faq.tsx
Labels: gssoc23, level3, wait for review

#563 making WhyChooseUs section responsive
  src/components/landing/WhyChooseUs.tsx
Labels: gssoc23, level1

#539 Navbar link issue #526 fixed
  src/components/landing/LandingNav.tsx
Labels: gssoc23, level1
